global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.3.136:9090']
     
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['192.168.3.136:8080']

  

